### ISSUE TITLE
Vista: Agregar producto

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-storeapp#13]
esta pantalla debe recibir por parmetro el id de la orden donde se agregara el producto.

![image](https://user-images.githubusercontent.com/69495972/98326326-f46d8e80-1fbe-11eb-8946-4d2596c1d0ca.png)

**Comment by CesarPava** [comment]
![1](https://user-images.githubusercontent.com/69518232/99211439-533cc000-2796-11eb-9a91-7b6c986ee7af.jpg)
![2](https://user-images.githubusercontent.com/69518232/99211448-5637b080-2796-11eb-928d-522bd7544070.jpg)
![3](https://user-images.githubusercontent.com/69518232/99211455-589a0a80-2796-11eb-8fa5-b74cfeee57ec.jpg)
