### ISSUE TITLE
Vista: Detalle orden tienda

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-storeapp#14]
cuando se termine de elegir todos los productos estos desaparecen y aparace el boton de finalizar.

en el header de la pantalla mostrar el total de los productos que faltan por elegir, el nombre del cliente y el total de la orden.

![image](https://user-images.githubusercontent.com/69495972/98326452-4e6e5400-1fbf-11eb-9098-73a186203a85.png)

en el footer centrado colocar el boton de agregar producto que llevara a la pantalla de agregar producto

**Comment by GilberttValentine** [comment]
![image](https://user-images.githubusercontent.com/69516529/99161966-12757600-26c6-11eb-8638-d98e0420d2af.png)
![image](https://user-images.githubusercontent.com/69516529/99161979-1dc8a180-26c6-11eb-9574-538a11e1ef2a.png)
![image](https://user-images.githubusercontent.com/69516529/99161985-23be8280-26c6-11eb-821e-d7a33f4a0695.png)
