### ISSUE TITLE
Vista: Ordenes de una tienda

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-storeapp#15]
esta pantalla tiene tres tabs los cuales son:
**en preparación**: ordenes que no se ha finalizado la eleccion de los productos.
**preparados**: que ya se eligieron todos los productos, aqui se muestra el boton de entregar
**entregados**: ordenes ya entregadas.

![image](https://user-images.githubusercontent.com/69495972/98326627-a60cbf80-1fbf-11eb-9ab2-84f52459db10.png)

del localStorage saca la tienda en sesion, ponerse deacuerdo con la persona responsable del login conque nombre se guardara la tienda en sesion

**Comment by Filowannabe** [comment]
![inpro - copia](https://user-images.githubusercontent.com/69178655/99178598-cbe24480-26e2-11eb-8934-2133a9db54eb.jpg)
![prep](https://user-images.githubusercontent.com/69178655/99178602-d0a6f880-26e2-11eb-852b-9ce2921bba69.jpg)
![Screenshot_11](https://user-images.githubusercontent.com/69178655/99178603-d3095280-26e2-11eb-8f91-2c5784d33356.jpg)
