### ISSUE TITLE
Vista-Registro Tienda

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-storeapp#16]
Registrar usuario en tienda
![image](https://user-images.githubusercontent.com/69495972/98326783-069bfc80-1fc0-11eb-82e4-bc2e7499b5cb.png)
cancelar lo lleva a la pantalla de login

**Comment by saralucia1224** [comment]
![image](https://user-images.githubusercontent.com/69540198/99323852-09f57a80-2841-11eb-9f98-55ea5178b224.png)
