### ISSUE TITLE
Login tienda

### ISSUE THREAD

**Issue by caferrerbeam** [eamquindio/diseno2020_2-mitienda-storeapp#17]
Login de la tienda, debe guardar en localStorage la tienda que inicio sesion.

![image](https://user-images.githubusercontent.com/69495972/98326857-364b0480-1fc0-11eb-9687-f2dcef0e9e28.png)

**Comment by saralucia1224** [comment]
![image](https://user-images.githubusercontent.com/69540198/99323820-f9dd9b00-2840-11eb-8ff6-4eca092f859b.png)
